import { createClientFromRequest } from 'npm:@base44/sdk@0.8.4';
import { jsPDF } from 'npm:jspdf@2.5.1';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const reportData = await req.json();

    const doc = new jsPDF();
    let yPos = 20;

    // Title
    doc.setFontSize(20);
    doc.setFont(undefined, 'bold');
    doc.text('Capital Works Planning Report', 20, yPos);
    yPos += 10;

    // Building and date info
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`Building: ${reportData.buildingName}`, 20, yPos);
    yPos += 6;
    doc.text(`Report Generated: ${reportData.generatedDate}`, 20, yPos);
    yPos += 6;
    doc.text(`Forecast Period: ${reportData.forecastPeriod}`, 20, yPos);
    yPos += 12;

    // Summary section
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('Executive Summary', 20, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`Total Active Assets: ${reportData.totalAssets}`, 30, yPos);
    yPos += 6;
    doc.text(`Critical Assets (Overdue): ${reportData.criticalAssets}`, 30, yPos);
    yPos += 6;
    doc.text(`Assets Due Within 3 Years: ${reportData.within3YearAssets}`, 30, yPos);
    yPos += 6;
    doc.text(`Total Forecast Budget: $${reportData.totalForecastCost.toLocaleString()}`, 30, yPos);
    yPos += 12;

    // Yearly breakdown
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('10-Year Forecast Breakdown', 20, yPos);
    yPos += 8;

    for (const yearData of reportData.yearlyBreakdown) {
      if (yearData.assetCount === 0) continue;

      // Check if we need a new page
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(12);
      doc.setFont(undefined, 'bold');
      doc.text(`${yearData.year}`, 20, yPos);
      yPos += 6;

      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      doc.text(`Assets: ${yearData.assetCount} | Total Cost: $${yearData.totalCost.toLocaleString()}`, 30, yPos);
      yPos += 6;

      // List assets
      yearData.assets.forEach((asset) => {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }

        doc.setFontSize(9);
        doc.text(`• ${asset.name} - ${asset.category}`, 40, yPos);
        yPos += 5;
        doc.text(`  Age: ${asset.age}y | Life Left: ${asset.remainingLife}y | Cost: $${asset.replacementCost.toLocaleString()} | Risk: ${asset.riskRating}`, 42, yPos);
        yPos += 6;
      });

      yPos += 4;
    }

    // Footer
    const pageCount = doc.internal.pages.length - 1;
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
      doc.text('Generated by Vivid BMS', 105, 290, { align: 'center' });
    }

    const pdfBytes = doc.output('arraybuffer');

    return new Response(pdfBytes, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename=capital-works-report-${reportData.buildingName.replace(/\s/g, '-')}-${Date.now()}.pdf`
      }
    });
  } catch (error) {
    console.error('Error generating report:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});